/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  start: [
    'start',
    {
      type: 'category',
      label: "项目能力",
      collapsed: false,
      items: [
        'start/feature/structure',
        'start/feature/plugin',
        'start/feature/lint',
        'start/feature/export',
        'start/feature/automatic', 
      ],
    },
    {
      type: 'category',
      label: "脚手架",
      collapsed: false,
      items: [
        'start/scaffold/Vitue-TDesign-Admin',
      ],
    },
  ],
  develop: [
    'develop',
    {
      type: 'autogenerated',
      dirName: 'develop',
    },
  ],
  guide: [
    'guide',
    {
      type: 'autogenerated',
      dirName: 'guide',
    },
  ],
  packages: [
    'packages',
    {
      type: 'autogenerated',
      dirName: 'packages',
    },
  ],
};

module.exports = sidebars;
